name: postgres18
services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: homeserver-pg-18
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    #ports:
      #- "${POSTGRES_HOST_PORT}:5432" # host port for debugging
    volumes:
      - postgres_data_18:/var/lib/postgresql
    networks:
      - gateway_net
      - postgres_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data_18:

networks:
  gateway_net:
    external: true
  postgres_net:
    external: true
